@baseURL = http://localhost:3000/api

# Create a new cart-item (requires product and user id)
POST {{baseURL}}/cart-item
Content-Type: application/json

{
  "userId": 1,
  "productId": 1,
  "quantity": 12
}

###

# Get cart-item info
GET {{baseURL}}/cart-item/1

###
GET {{baseURL}}/cart-item/1?sortOrder=DESC


###

# Delete cart-item
DELETE {{baseURL}}/cart-item/1/26